-- Initial data is created safely by the on_auth_user_created trigger defined in
-- migrations/002_production_hardening.sql. Existing authenticated users are
-- initialized idempotently by calling the initialize_user_data() RPC at login.
-- No fixed user UUID or secret is stored in this file.
