-- KAZUAKI LIFE HUB Phase 1 schema
create extension if not exists pgcrypto;

create table profiles(id uuid primary key references auth.users(id) on delete cascade, display_name text, location text, occupation text, ana_status text default 'Diamond', current_pp integer default 0, target_pp integer default 100000, has_sfc boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table cards(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, card_type text check(card_type in('personal','business')), primary_use text, annual_fee numeric default 0, monthly_spend numeric default 0, annual_spend numeric default 0, points_earned numeric default 0, benefits_status jsonb default '{}', recovery_rating text, renewal_decision text, notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table card_transactions(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, card_id uuid references cards(id) on delete cascade, amount numeric not null, merchant text, category text, transacted_at date not null, notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table card_benefits(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, card_id uuid references cards(id) on delete cascade, name text not null, estimated_value numeric default 0, used_at date, expires_at date, status text default 'available', created_at timestamptz default now(), updated_at timestamptz default now());
create table points_accounts(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, program_name text not null, balance numeric default 0, target_balance numeric default 0, last_updated_at timestamptz default now(), notes text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(user_id,program_name));
create table points_transactions(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, account_id uuid references points_accounts(id) on delete cascade, amount numeric not null, transaction_type text check(transaction_type in('earn','redeem','adjust')), occurred_at date default current_date, notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table trips(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, departure_date date, return_date date, destination text, companions text[], airline text, flight_number text, hotel text, reservation_number text, points_used numeric default 0, miles_used numeric default 0, budget numeric default 0, actual_cost numeric default 0, notes text, status text check(status in('considering','booked','traveling','completed')), created_at timestamptz default now(), updated_at timestamptz default now());
create table trip_members(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, trip_id uuid references trips(id) on delete cascade, name text not null, relationship text, created_at timestamptz default now(), updated_at timestamptz default now());
create table travel_bookings(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, trip_id uuid references trips(id) on delete cascade, booking_type text, provider text, confirmation_number text, starts_at timestamptz, ends_at timestamptz, amount numeric default 0, details jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table news_categories(id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, name text not null, slug text not null, enabled boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table news_sources(id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, name text not null, source_url text, feed_url text, category_id uuid references news_categories(id), enabled boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table news_items(id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, source_id uuid references news_sources(id), category_id uuid references news_categories(id), source_name text, source_url text, title text not null, summary text, ai_summary text, published_at timestamptz, importance text default 'medium', original_url text, image_url text, is_read boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table saved_news(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, news_item_id uuid references news_items(id) on delete cascade, read_later boolean default false, is_favorite boolean default true, created_at timestamptz default now(), updated_at timestamptz default now(), unique(user_id,news_item_id));
create table daily_briefs(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, brief_date date default current_date, content text not null, source_item_ids uuid[], model text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(user_id,brief_date));
create table camera_gear(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, gear_type text check(gear_type in('camera','lens','accessory')), maker text default 'SONY', model text not null, serial_number text, purchased_at date, notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table camera_presets(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, gear_id uuid references camera_gear(id) on delete set null, name text not null, purpose text, location text, settings jsonb default '{}', is_favorite boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table app_settings(id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, theme text default 'system', brief_enabled boolean default true, brief_time time default '07:00', notification_settings jsonb default '{}', news_preferences jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table notifications(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, body text, notification_type text, is_read boolean default false, action_url text, scheduled_at timestamptz, sent_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());

-- Every table is private to its owner. Global news/category/source rows (user_id null) are readable.
alter table profiles enable row level security;
create policy "owner_profile" on profiles for all using(id=auth.uid()) with check(id=auth.uid());
do $$ declare t text; begin foreach t in array array['cards','card_transactions','card_benefits','points_accounts','points_transactions','trips','trip_members','travel_bookings','news_categories','news_sources','news_items','saved_news','daily_briefs','camera_gear','camera_presets','app_settings','notifications'] loop execute format('alter table %I enable row level security',t); execute format('create policy "owner_all" on %I for all using (user_id = auth.uid()) with check (user_id = auth.uid())',t); end loop; end $$;
create policy "public_categories_read" on news_categories for select using(user_id is null);
create policy "public_sources_read" on news_sources for select using(user_id is null);
create policy "public_news_read" on news_items for select using(user_id is null);

-- Keep audit timestamps accurate and make per-user queries efficient.
create or replace function public.set_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;
do $$ declare t text; begin
  foreach t in array array['profiles','cards','card_transactions','card_benefits','points_accounts','points_transactions','trips','trip_members','travel_bookings','news_categories','news_sources','news_items','saved_news','daily_briefs','camera_gear','camera_presets','app_settings','notifications'] loop
    execute format('create trigger set_%I_updated_at before update on %I for each row execute function public.set_updated_at()',t,t);
  end loop;
  foreach t in array array['cards','card_transactions','card_benefits','points_accounts','points_transactions','trips','trip_members','travel_bookings','news_categories','news_sources','news_items','saved_news','daily_briefs','camera_gear','camera_presets','app_settings','notifications'] loop
    execute format('create index %I_user_id_idx on %I(user_id)',t,t);
  end loop;
end $$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1))); insert into app_settings(user_id) values(new.id); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
